# Generated by Django 5.1.7 on 2025-03-15 19:35

import django_mongodb_backend.fields
from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField(blank=True)),
                (
                    "features",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        blank=True, embedded_model=recipes.models.Features, null=True
                    ),
                ),
                (
                    "ingredients",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "embedding_ingredients",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("voyage_embedding", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "recipes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preparation_time", models.CharField(max_length=100)),
                ("complexity", models.CharField(max_length=100)),
                ("prep_time", models.IntegerField()),
                ("cuisine", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
